name: Deploy to Raiola
on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy Detective
    runs-on: ubuntu-latest
    steps:
    - name: ðŸšš Obtener cÃ³digo
      uses: actions/checkout@v4

    - name: ðŸŸ¢ Instalar PNPM 9
      uses: pnpm/action-setup@v3
      with:
        version: 9

    - name: ðŸŸ¢ Instalar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'

    - name: ðŸ”¨ Instalar y Construir (Desde la RaÃ­z)
      run: |
        pnpm install --no-frozen-lockfile
        pnpm run build
        
        echo "================ DONDE ESTA DIST? ================"
        ls -la
        ls -la client/
        echo "=================================================="

    - name: ðŸ“‚ Subir a FTP (Intento Client)
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./client/dist/    # Probamos aquÃ­ primero
        server-dir: ./
