name: Deploy to Raiola
on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: ğŸ‰ Deploy Client
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Obtener cÃ³digo
      uses: actions/checkout@v4

    - name: ğŸŸ¢ Instalar PNPM (VersiÃ³n 9)
      uses: pnpm/action-setup@v3
      with:
        version: 9                # <--- Â¡AQUÃ ESTÃ EL CAMBIO MÃGICO!

    - name: ğŸŸ¢ Instalar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'

    - name: ğŸ”¨ Instalar y Construir
      run: |
        # Instalamos desde la raÃ­z para que funcionen los parches del workspace
        pnpm install --no-frozen-lockfile
        
        # Entramos a la carpeta del cliente para construir la web
        cd client
        pnpm run build

    - name: ğŸ“‚ Subir a FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./client/dist/
        server-dir: ./
