name: Deploy to Raiola
on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 游꿀 Deploy Client
    runs-on: ubuntu-latest
    steps:
    - name: 游뚴 Obtener c칩digo
      uses: actions/checkout@v4

    - name: 游릭 Instalar PNPM
      uses: pnpm/action-setup@v3
      with:
        version: 8

    - name: 游릭 Instalar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'

    - name: 游댣 Instalar y Construir
      run: |
        pnpm install
        cd client
        pnpm run build
        ls -la dist  # Esto nos confirmar치 en el log que la carpeta existe

    - name: 游늭 Subir a FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./client/dist/
        server-dir: ./
