name: Deploy to Raiola
on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: ğŸ‰ Deploy Final
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Obtener cÃ³digo
      uses: actions/checkout@v4

    - name: ğŸŸ¢ Instalar PNPM 9
      uses: pnpm/action-setup@v3
      with:
        version: 9

    - name: ğŸŸ¢ Instalar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'

    - name: ğŸ”¨ Instalar y Construir (EN LA RAÃZ)
      run: |
        pnpm install --no-frozen-lockfile
        pnpm run build

    - name: ğŸ“‚ Subir a FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        # ğŸ‘‡ Â¡AQUÃ ESTÃ EL TRUCO! ğŸ‘‡
        # AÃ±adimos 'public/' para que suba solo el contenido final
        local-dir: ./dist/public/
        server-dir: ./cerrajerosenchamartin.madrid/
