name: Deploy to Raiola
on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy Client
    runs-on: ubuntu-latest
    steps:
    - name: ðŸšš Obtener cÃ³digo
      uses: actions/checkout@v4

    - name: ðŸŸ¢ Instalar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: ðŸ”¨ Instalar y Construir (Dentro de Client)
      run: |
        cd client
        npm install --legacy-peer-deps
        npm run build

    - name: ðŸ“‚ Subir a FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./client/dist/    # <--- Â¡AquÃ­ estaba la clave!
        server-dir: ./
